resources/site/getting-started.md, resources/site/how-to.md
Documentation only change
```
[ ] Bugfix
[ ] Feature
```
Issue Number: n/a
```
[ ] Yes
[x] No
```
=> Improve documentation of lazy loaded modules

projects/scion/workbench/src/lib/ui/viewport/viewport.component.scss, resources/site/_changelog-next-release.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: #14
```
[ ] Yes
[x] No
```
=> Use momentum-based scrolling in iOS

projects/scion/workbench/src/lib/spec/lazy-loaded-view-injection.spec.ts, projects/scion/workbench/src/lib/workbench-view-registry.service.ts, resources/site/_changelog-next-release.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: #21 
```
[ ] Yes
[x] No
```
=> Allow lazily-loaded views to inject masked injection tokens (#21)

projects/scion/workbench/src/lib/view-part/view-tab/view-tab.component.ts
[x] Bugfix
[ ] Feature
```
Issue Number: 24
```
[ ] Yes
[x ] No
```
=> Prevent dblclick event being handled by view tab when only clicked once (#24)

projects/scion/workbench/package.json, resources/site/_changelog-next-release.md, resources/site/changelog.md
```
[ ] Bugfix
[ ] Feature
[x] Release to 0.0.0-beta.11
```
```
[ ] Yes
[x] No
```
=> Release version 0.0.0-beta.11

projects/scion/workbench/src/lib/activity-part/activity-part.component.html, projects/scion/workbench/src/lib/activity-part/activity-part.component.ts, projects/scion/workbench/src/lib/activity-part/activity.ts, projects/scion/workbench/src/lib/activity-part/wb-activity-action.directive.ts, projects/scion/workbench/src/lib/activity-part/wb-activity.directive.ts, projects/scion/workbench/src/lib/activity-part/workbench-activity-part.service.ts, projects/scion/workbench/src/lib/disposable.ts, projects/scion/workbench/src/lib/routing/activity.resolver.ts, projects/scion/workbench/src/lib/routing/workbench-auxiliary-routes-registrator.service.ts, projects/scion/workbench/src/lib/spec/activity-guard.spec.ts, projects/scion/workbench/src/lib/spec/activity.spec.ts, projects/scion/workbench/src/lib/workbench.component.ts, projects/scion/workbench/src/lib/workbench.constants.ts, projects/scion/workbench/src/lib/workbench.module.ts, projects/scion/workbench/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #28 
```
[x] Yes
[ ] No
```
- Use `visible` property added to `WbActivityDirective` over `ngIf` directive to show or hide an activity based on a conditional:
`<wb-activity [visible]="conditional"></wb-activity>`
- activity route provides the activity in its routing context
- activity actions can be specified as component or template
- activity visibility is controlled on the activity
=> Allow programmatic registration of activities (#28)

projects/scion/workbench/src/lib/routing/view-outlet-url-observer.service.ts, projects/scion/workbench/src/lib/routing/view-registry-synchronizer.service.ts, projects/scion/workbench/src/lib/routing/workbench-auxiliary-routes-registrator.service.ts, projects/scion/workbench/src/lib/routing/workbench-router.service.ts, projects/scion/workbench/src/lib/view-part-grid/view-part-grid-url-observer.service.ts, projects/scion/workbench/src/lib/view-part-grid/view-part-grid.model.ts, projects/scion/workbench/src/lib/view/view.component.ts, projects/scion/workbench/src/lib/workbench-view-registry.service.ts, projects/scion/workbench/src/lib/workbench.model.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #29 
```
[ ] Yes
[x] No
```
=> Register view auxiliary routes via `WorkbenchAuxiliaryRoutesRegistrator` and set view active state upon view creation

projects/scion/workbench/src/lib/message-box/message-box.component.ts, projects/scion/workbench/src/lib/message-box/message-box.service.ts, projects/scion/workbench/src/lib/message-box/message-box.ts, projects/scion/workbench/src/lib/view/view.component.scss, projects/scion/workbench/src/lib/view/view.component.ts, projects/scion/workbench/src/lib/workbench.component.scss, projects/scion/workbench/src/lib/workbench.component.ts, projects/scion/workbench/src/lib/workbench.config.ts, projects/scion/workbench/src/lib/workbench.constants.ts, projects/scion/workbench/src/public_api.ts, resources/site/how-to.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #32 
```
[x] Yes
[ ] No
```
Message box action texts are no longer specified when importing the workbench module. Instead, message box texts are provided directly when spawning the message box.
=> Provide message box action texts when spawning the message box (#32)

projects/scion/workbench/src/lib/view-part/view-tab/view-tab.component.scss
```
[x] Bugfix
[ ] Feature
```
Issue Number: #33 
```
[ ] Yes
[x] No
```
=> Disable vertical scrolling in workbench viewtab bar (#33)

angular.json, package.json, projects/scion/dimension/karma.conf.js, projects/scion/dimension/ng-package.json, projects/scion/dimension/package.json, projects/scion/dimension/src/lib/dimension.directive.ts, projects/scion/dimension/src/lib/dimension.module.ts, projects/scion/dimension/src/public_api.ts, projects/scion/dimension/src/test.ts, projects/scion/dimension/tsconfig.lib.json, projects/scion/dimension/tsconfig.spec.json, projects/scion/dimension/tslint.json, projects/scion/workbench/package.json, projects/scion/workbench/src/lib/ui/viewport/viewport.component.ts, projects/scion/workbench/src/lib/ui/viewport/viewport.module.ts, projects/scion/workbench/src/lib/view-part/view-list/view-list.component.ts, projects/scion/workbench/src/lib/workbench.module.ts, projects/scion/workbench/src/public_api.ts, resources/site/getting-started.md, resources/site/how-to.md, tsconfig.json
```
[ ] Bugfix
[x] Feature
```
Issue Number: #44
```
[x] Yes
[ ] No
```
Workbench requires `@scion/dimension` as its peer-dependency which you can install as following:
`npm install --save @scion/dimension`
=> Extract `sci-dimension-module` into a separate NPM library

.travis.yml, CONTRIBUTING.md, projects/scion/dimension/README.md, projects/scion/mouse-dispatcher/README.md, projects/scion/viewport/README.md
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Issue Number: #56 
```
[ ] Yes
[x] No
```
=> Deploy npm packages to http://npmjs.org on git tag using travis-ci (#56)

projects/scion/workbench/src/lib/view-part/view-list-button/view-list-button.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #42
```
[ ] Yes
[x] No
```
=> Specify view-list dropdown anchor as `ElementRef` instead of native element to be compatible with Angular CDK 6

package-lock.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Issue Number: #59 
```
[ ] Yes
[x] No
```
=> Use puppeteer to run automated tests (#59)

projects/scion/workbench/src/lib/routing/workbench-auxiliary-routes-registrator.service.ts, projects/scion/workbench/src/lib/workbench.module.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #28 
```
[ ] Yes
[x] No
```
=> Register activity auxiliary routes only in root injector (#28)

projects/scion/workbench/src/lib/view-part/view-tab/view-tab.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #24
```
[ ] Yes
[x] No
```
=> Do not enter minimize mode when closing views quickly in maximize mode (#24)

projects/scion/workbench/src/lib/popup/metadata.ts, projects/scion/workbench/src/lib/popup/popup.service.ts, projects/scion/workbench/src/lib/workbench.module.ts, projects/scion/workbench/src/public_api.ts, projects/scion/workbench/src/theme/_popup-theme.scss, projects/scion/workbench/src/theme/_theming.scss
```
[ ] Bugfix
[x] Feature
```
Issue Number: #76 
```
[ ] Yes
[x] No
```
=> feat: allow to display a component in a popup

projects/scion/mouse-dispatcher/src/lib/mouse-dispatcher.ts, projects/scion/viewport/src/lib/scrollbar/scrollbar.component.ts, projects/scion/workbench/src/lib/remote-site/remote-site.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #86 
```
[ ] Yes
[x] No
```
=> fix: reduce the number of 'mousemove' events dispatched between application windows

README.md
Added a disclaimer for currently supported browsers in README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: add disclaimer to README.md

package.json, projects/app/workbench-application-platform/common/package.json, projects/scion/dimension/package.json, projects/scion/mouse-dispatcher/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform.api/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench-application.core/package.json, projects/scion/workbench/package.json, resources/site/changelog.md
```
[ ] Bugfix
[ ] Feature
[x] Release
```
```
[ ] Yes
[x] No
```
=> release: version 0.0.0-beta.16

projects/scion/workbench-application.core/src/lib/intent-service.ts, projects/scion/workbench/src/lib/activity-part/wb-activity.directive.ts, projects/scion/workbench/src/lib/spec/activities-from-lazy-loaded-modules.spec.ts, projects/scion/workbench/src/lib/spec/activity-action.spec.ts, projects/scion/workbench/src/lib/spec/activity-guard.spec.ts, projects/scion/workbench/src/lib/spec/activity.spec.ts, projects/scion/workbench/src/lib/spec/lazy-loaded-view-injection.spec.ts, projects/scion/workbench/src/lib/spec/wb-route-reuse-strategy.spec.ts, resources/site/getting-started/workbench-application-platform/getting-started.md, resources/site/getting-started/workbench/getting-started.md, resources/site/how-to/workbench-application-platform/how-to-configure-routing-in-the-sub-application.md, resources/site/how-to/workbench-application-platform/how-to-interact-with-the-platform.md, resources/site/how-to/workbench-application-platform/how-to-issue-custom-intent.md, resources/site/how-to/workbench-application-platform/how-to-provide-a-custom-activity-action.md, resources/site/how-to/workbench-application-platform/how-to-provide-a-view-capability.md, resources/site/how-to/workbench-application-platform/how-to-provide-an-activity-capability.md, resources/site/how-to/workbench/how-to-add-an-activity.md, resources/site/how-to/workbench/how-to-open-a-view.md, resources/site/workbench-application-platform.md, resources/site/workbench.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> Simplify and clarify some paragraphs in the documentation

package.json, projects/app/workbench-application-platform/common/package.json, projects/scion/dimension/package.json, projects/scion/mouse-dispatcher/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform.api/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench-application.core/package.json, projects/scion/workbench/package.json, resources/site/changelog.md
release: version 0.0.0-beta.17
=> release: version 0.0.0-beta.17

projects/app/common/src/lib/params-enter/params-enter.component.html, projects/app/workbench/workbench-app/src/app/app-routing.module.ts, projects/app/workbench/workbench-app/src/app/app.module.ts, projects/app/workbench/workbench-app/src/app/view-navigation/view-navigation.component.html, projects/app/workbench/workbench-app/src/app/view-navigation/view-navigation.component.scss, projects/app/workbench/workbench-app/src/app/view-navigation/view-navigation.component.ts, projects/app/workbench/workbench-app/src/app/view/view.component.html, projects/app/workbench/workbench-app/src/app/view/view.component.scss, projects/app/workbench/workbench-app/src/app/view/view.component.ts, projects/app/workbench/workbench-app/src/app/welcome-page/welcome-page.component.html, projects/app/workbench/workbench-app/src/app/welcome-page/welcome-page.component.scss, projects/app/workbench/workbench-app/src/app/welcome-page/welcome-page.component.ts, projects/e2e/workbench/src/page-object/sci-params-enter.po.ts, projects/e2e/workbench/src/page-object/sci-property.po.ts, projects/e2e/workbench/src/page-object/view-navigation.po.ts, projects/e2e/workbench/src/router.e2e-spec.ts, projects/scion/workbench/src/lib/routing/workbench-router.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #120 
```
[ ] Yes
[x] No
```
=> fix: match matrix params when resolving views for activation or closing

package-lock.json, package.json, projects/app/common/package.json, projects/scion/dimension/package.json, projects/scion/mouse-dispatcher/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform.api/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench-application.core/package.json, projects/scion/workbench/package.json, resources/site/changelog.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Release
```
```
[ ] Yes
[x] No
```
=> release: version 0.0.0-beta.20

CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: xxx
```
[ ] Yes
[x] No
```
=> docs: refine release guidelines

projects/app/common/package.json, projects/scion/dimension/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench/package.json
```
[ ] Bugfix
[ ] Feature
[x] Remove support for Angular 7
```
Issue Number: #147 
```
[x] Yes
[ ] No
```
=> feat: remove support for Angular 7

package.json, projects/scion/dimension/src/lib/dimension.directive.ts, projects/scion/dimension/src/lib/dimension.service.spec.ts, projects/scion/dimension/src/lib/dimension.service.ts, projects/scion/dimension/src/lib/mutation.service.ts, projects/scion/dimension/src/public_api.ts, projects/scion/dimension/tslint.json, projects/scion/viewport/src/lib/scrollbar/scrollbar.component.html, projects/scion/viewport/src/lib/scrollbar/scrollbar.component.scss, projects/scion/viewport/src/lib/scrollbar/scrollbar.component.ts, projects/scion/viewport/src/lib/viewport.component.html, projects/scion/viewport/src/lib/viewport.component.scss, projects/scion/viewport/src/lib/viewport.component.spec.ts, projects/scion/viewport/src/lib/viewport.component.ts, projects/scion/viewport/tslint.json, projects/scion/workbench/src/lib/view-part/view-list/view-list.component.scss, projects/scion/workbench/src/lib/view-part/view-part-bar/view-part-bar.component.html, projects/scion/workbench/src/lib/view-part/view-part-bar/view-part-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #156
```
[x] Yes
[ ] No
```
=> fix: observe element dimension changes natively

projects/e2e/workbench/src/view-tab-bar.e2e-spec.ts, projects/scion/workbench-application-platform/src/lib/spec/manifest-collector.spec.ts, projects/scion/workbench-application-platform/src/lib/spec/workbench-application-platform.module.spec.ts, projects/scion/workbench/src/lib/spec/activities-from-lazy-loaded-modules.spec.ts, projects/scion/workbench/src/lib/spec/activity-action.spec.ts, projects/scion/workbench/src/lib/spec/activity-guard.spec.ts, projects/scion/workbench/src/lib/spec/activity.spec.ts, projects/scion/workbench/src/lib/spec/lazy-loaded-view-injection.spec.ts, projects/scion/workbench/src/lib/spec/route-resolve.spec.ts, projects/scion/workbench/src/lib/spec/router-navigate.spec.ts, projects/scion/workbench/src/lib/spec/view-part-grid.component.spec.ts, projects/scion/workbench/src/lib/spec/view-part-grid.spec.ts, projects/scion/workbench/src/lib/spec/view.component.spec.ts, projects/scion/workbench/src/lib/spec/views-from-lazy-loaded-modules.spec.ts, projects/scion/workbench/src/lib/spec/wb-route-reuse-strategy.spec.ts, projects/scion/workbench/src/lib/spec/workbench-testing.module.ts, projects/scion/workbench/src/lib/view-activation-instant-provider.service.ts, projects/scion/workbench/src/lib/view-part-grid/view-part-grid.model.ts, projects/scion/workbench/src/lib/workbench-url-observer.service.ts, projects/scion/workbench/src/lib/workbench-view-registry.service.ts, projects/scion/workbench/src/lib/workbench.model.ts, projects/scion/workbench/src/lib/workbench.module.ts, projects/scion/workbench/src/public_api.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #74 
```
[ ] Yes
[x] No
```
=> feat: view tab activation history

projects/app/workbench-application-platform/testing-app/src/app/testing/message-box-panel/message-box-panel.component.html, projects/e2e/workbench-application-platform/src/page-object/message-box-panel.po.ts, projects/scion/workbench/src/lib/message-box/message-box.component.html, projects/scion/workbench/src/lib/message-box/message-box.component.scss
```
[x] Bugfix
[ ] Feature
```
Issue Number: #131
```
[ ] Yes
[x] No
```
=> fix: preserve line-breaks in message box content

projects/app/workbench-application-platform/testing-app/src/app/testing/testing-routing.module.ts, projects/app/workbench-application-platform/testing-app/src/app/testing/testing.module.ts, projects/app/workbench-application-platform/testing-app/src/app/testing/view-b8bbbb11/view-b8bbbb11.component.html, projects/app/workbench-application-platform/testing-app/src/app/testing/view-b8bbbb11/view-b8bbbb11.component.ts, projects/app/workbench-application-platform/testing-app/src/assets/manifest.json, projects/app/workbench/workbench-app/src/app/app-routing.module.ts, projects/app/workbench/workbench-app/src/app/app.module.ts, projects/app/workbench/workbench-app/src/app/view-bb9700a6/view-bb9700a6.component.html, projects/app/workbench/workbench-app/src/app/view-bb9700a6/view-bb9700a6.component.ts, projects/e2e/workbench-application-platform/src/page-object/testcase-b8bbbb11-view.po.ts, projects/e2e/workbench-application-platform/src/router-link.e2e-spec.ts, projects/e2e/workbench-application-platform/src/util/testing.util.ts, projects/e2e/workbench/src/page-object/testcase-bb9700a6-view.po.ts, projects/e2e/workbench/src/router-link.e2e-spec.ts, projects/e2e/workbench/src/util/testing.util.ts, projects/scion/workbench-application.angular/src/lib/workbench-router-link.directive.ts, projects/scion/workbench/src/lib/routing/wb-router-link.directive.ts, resources/site/how-to/workbench-application-platform/how-to-navigate-to-a-view.md, resources/site/how-to/workbench/how-to-open-a-view.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: #155
```
[ ] Yes
[x] No
```
=> fix: support mac command key when opening view in new view tab

projects/scion/workbench-application-platform.api/src/lib/core.model.ts, projects/scion/workbench-application-platform/src/lib/activity-capability/activity-registrator.service.ts, projects/scion/workbench-application-platform/src/lib/core/array.util.ts, projects/scion/workbench-application-platform/src/lib/core/intent-handler-registrator.service.ts, projects/scion/workbench-application-platform/src/lib/core/manifest-registry.service.ts, projects/scion/workbench-application-platform/src/lib/core/message-bus.service.ts, projects/scion/workbench-application-platform/src/lib/core/metadata.ts, projects/scion/workbench-application-platform/src/lib/core/qualifier-tester.ts, projects/scion/workbench-application-platform/src/lib/manifest-capability/manifest-registry-intent-handler.service.ts, projects/scion/workbench-application-platform/src/lib/popup-capability/popup-capability.module.ts, projects/scion/workbench-application-platform/src/lib/popup-capability/popup-intent-dispatcher.service.ts, projects/scion/workbench-application-platform/src/lib/spec/array.util.spec.ts, projects/scion/workbench-application-platform/src/lib/spec/manifest-registry.spec.ts, projects/scion/workbench-application-platform/src/lib/spec/message-bus.spec.ts, projects/scion/workbench-application-platform/src/lib/spec/qualifier.spec.ts, projects/scion/workbench-application-platform/src/lib/view-capability/view-capability.module.ts, projects/scion/workbench-application-platform/src/lib/view-capability/view-intent-dispatcher.service.ts, projects/scion/workbench-application.core/src/lib/manifest-registry.service.ts, resources/site/getting-started/workbench-application-platform/getting-started.md, resources/site/how-to/workbench-application-platform/how-to-install-a-programmatic-intent-handler.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #154, #173 
```
[x] Yes
[ ] No
```
=> feat: allow specifying an optional capability qualifier value

projects/scion/workbench-application.core/src/lib/platform.ts, resources/site/how-to/workbench-application-platform/how-to-interact-with-the-platform.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #130
```
[ ] Yes
[x] No
```
=> feat: add API to query if micro-frontend is running standalone

package-lock.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
Issue Number: #182
```
[ ] Yes
[x] No
```
=> fix: use correct registry in package-lock.json

projects/scion/workbench/src/lib/view-part/view-part.component.html, projects/scion/workbench/src/lib/view-part/view-part.component.scss
```
[x] Bugfix
[ ] Feature
```
Issue Number: #129
```
[ ] Yes
[x] No
```
=> fix: show entry point page inside a viewport

.editorconfig.intellij.xml, projects/scion/workbench-application-platform.api/src/lib/manifest-registry.model.ts, projects/scion/workbench-application-platform/src/lib/core/manifest-registry.service.ts, projects/scion/workbench-application-platform/src/lib/manifest-capability/manifest-registry-intent-handler.service.ts, projects/scion/workbench-application-platform/src/lib/spec/manifest-registry.spec.ts, projects/scion/workbench-application.core/src/lib/manifest-registry.service.ts, projects/scion/workbench-application.core/src/lib/message-bus.service.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #189
```
[ ] Yes
[x] No
```
=> feat: allow to register and unregister capabilities from a micro frontend

projects/app/workbench-application-platform/dev-tools-app/src/app/dev-tools/capability-accordion-panel/capability-accordion-panel.component.html, projects/app/workbench-application-platform/dev-tools-app/src/app/dev-tools/capability-accordion-panel/capability-accordion-panel.component.scss, projects/app/workbench-application-platform/dev-tools-app/src/app/dev-tools/dev-tools/dev-tools.component.html, projects/app/workbench-application-platform/testing-app/src/app/testing/activator.module.ts, projects/app/workbench-application-platform/testing-app/src/app/testing/testing-routing.module.ts, projects/app/workbench-application-platform/testing-app/src/assets/manifest.json, projects/scion/workbench-application-platform.api/src/lib/activator.model.ts, projects/scion/workbench-application-platform.api/src/lib/core.model.ts, projects/scion/workbench-application-platform.api/src/public_api.ts, projects/scion/workbench-application-platform/src/lib/activator-capability/activator-capability.module.ts, projects/scion/workbench-application-platform/src/lib/activator-capability/activator-outlet/activator-outlet.component.html, projects/scion/workbench-application-platform/src/lib/activator-capability/activator-outlet/activator-outlet.component.scss, projects/scion/workbench-application-platform/src/lib/activator-capability/activator-outlet/activator-outlet.component.ts, projects/scion/workbench-application-platform/src/lib/activator-capability/microfrontend-activator.service.ts, projects/scion/workbench-application-platform/src/lib/manifest-capability/manifest-registry-intent-handler.service.ts, projects/scion/workbench-application-platform/src/lib/workbench-application-platform.module.ts, resources/site/how-to/workbench-application-platform/how-to-provide-an-activator-capability.md, resources/site/how-to/workbench-application-platform/how-to.md
```
[ ] Bugfix
[x] Feature
```
Issue Number: #190
```
[ ] Yes
[x] No
```
=> feat: allow a micro frontend to provide activator loaded at platform startup

projects/app/workbench-application-platform/dev-tools-app/src/app/dev-tools/capability-accordion-panel/capability-accordion-panel.component.html, projects/app/workbench-application-platform/dev-tools-app/src/app/dev-tools/capability-accordion-panel/capability-accordion-panel.component.scss, projects/scion/workbench-application-platform.api/src/lib/manifest-registry.model.ts, projects/scion/workbench-application-platform/src/lib/core/app-outlet.directive.ts, projects/scion/workbench-application-platform/src/lib/core/manifest-registry.service.ts, projects/scion/workbench-application-platform/src/lib/core/qualifier-tester.ts, projects/scion/workbench-application-platform/src/lib/manifest-capability/manifest-registry-intent-handler.service.ts, projects/scion/workbench-application-platform/src/lib/spec/manifest-registry.spec.ts, projects/scion/workbench-application-platform/src/lib/spec/qualifier.spec.ts, projects/scion/workbench-application.core/src/lib/manifest-registry.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #199, #200, #201
```
[ ] Yes
[x] No
```
=> Fixes for issues 199, 200, 201

projects/scion/dimension/src/lib/dimension.service.spec.ts
fixes: #205
```
[ ] Bugfix
[ ] Feature
[x] Test
```
Issue Number: #205
```
[ ] Yes
[x] No
```
=> test: remove fit constraint in spec to run all specs

projects/scion/workbench-application-platform.api/src/lib/view.model.ts, projects/scion/workbench-application-platform/src/lib/view-capability/view-intent-dispatcher.service.ts, projects/scion/workbench-application.angular/src/lib/workbench-router.service.ts, projects/scion/workbench-application.core/src/lib/router.service.ts
fixes: #207
```
[ ] Bugfix
[x] Feature
```
Issue Number: #207
```
[ ] Yes
[x] No
```
=> feat: allow a microfrontend to open a view in a specific view outlet

projects/scion/workbench-application-platform.api/src/lib/view.model.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #207
```
[ ] Yes
[x] No
```
=> fix: declare the type `viewref` to be of type `string` instead of a string literal

README.md
```
[ ] Bugfix
[ ] Feature
```
Issue Number: xxx
```
[ ] Yes
[x] No
```
=> docs: add angular 9 compatibility note for version 0.0.0.beta.33 or newer

CHANGELOG.md, docs/site/changelog/changelog.md, package-lock.json, package.json, projects/app-common/package.json, projects/scion/dimension/package.json, projects/scion/mouse-dispatcher/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform.api/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench-application.core/package.json, projects/scion/workbench/package.json
=> release: v0.0.0-beta.34

CHANGELOG.md, README.md, docs/site/changelog/changelog.md, package.json, projects/app-common/package.json, projects/scion/dimension/package.json, projects/scion/mouse-dispatcher/package.json, projects/scion/viewport/package.json, projects/scion/workbench-application-platform.api/package.json, projects/scion/workbench-application-platform/package.json, projects/scion/workbench-application.angular/package.json, projects/scion/workbench-application.core/package.json, projects/scion/workbench/package.json
=> release: v0.0.0-beta.35

CHANGELOG.md, docs/site/changelog/changelog.md, package-lock.json, package.json, projects/scion/workbench/package.json
Please refer to the changelog which you find [here](https://github.com/SchweizerischeBundesbahnen/scion-workbench/blob/master/docs/site/changelog/changelog.md).
=> release: v11.0.0-beta.1

CHANGELOG_WORKBENCH_CLIENT.md, docs/site/changelog-workbench-client/changelog.md, projects/scion/workbench-client/package.json
=> release(workbench-client): v1.0.0-beta.2

CHANGELOG_WORKBENCH.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v11.0.0-beta.3

.github/workflows/workflow.yml, CONTRIBUTING.md, README.md, apps/workbench-client-testing-app/src/environments/environment.vercel.ts, apps/workbench-testing-app/src/assets/manifest-devtools.json, apps/workbench-testing-app/src/assets/manifest-microfrontend-platform-testing-app.json, apps/workbench-testing-app/src/environments/environment.vercel.ts, docs/site/announcements.md, projects/scion/workbench-client/src/lib/workbench-client.ts, projects/scion/workbench/src/lib/microfrontend-platform/initialization/ng-zone-decorators.ts
=> chore: migrate vercel deployments to the updated url format

CHANGELOG_WORKBENCH_CLIENT.md, docs/site/changelog-workbench-client/changelog.md, projects/scion/workbench-client/package.json
=> release(workbench-client): v1.0.0-beta.7

CHANGELOG_WORKBENCH.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v11.0.0-beta.8

CHANGELOG_WORKBENCH.md, README.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v12.0.0-beta.1

docs/site/projects-overview.md
=> docs: correct incorrect usages of the word "agnostic"

CHANGELOG_WORKBENCH_CLIENT.md, docs/site/changelog-workbench-client/changelog.md, projects/scion/workbench-client/package.json
=> release(workbench-client): v1.0.0-beta.8

CHANGELOG_WORKBENCH.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v12.0.0-beta.2

apps/workbench-client-testing-app/src/app/register-workbench-capability-page/register-workbench-capability-page.component.html, apps/workbench-client-testing-app/src/app/register-workbench-capability-page/register-workbench-capability-page.component.ts, apps/workbench-testing-app/src/app/workbench-manifest.ts
=> [testing Apps] migrate deprecated capability parameter declarations

CHANGELOG_WORKBENCH.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v12.0.0-beta3

apps/workbench-client-testing-app/src/app/router-page/router-page.component.ts, apps/workbench-client-testing-app/src/app/util/append-param-data-type.pipe.ts, apps/workbench-client-testing-app/src/app/util/util.module.ts, apps/workbench-client-testing-app/src/app/util/util.ts, apps/workbench-client-testing-app/src/app/view-page/view-page.component.html, apps/workbench-client-testing-app/src/app/view-page/view-page.component.ts, projects/scion/e2e-testing/src/workbench-client/router-params.e2e-spec.ts, projects/scion/e2e-testing/src/workbench-client/router.e2e-spec.ts, projects/scion/workbench-client/src/lib/routing/workbench-router.ts, projects/scion/workbench/src/lib/microfrontend-platform/microfrontend-view/microfrontend-view.component.ts, projects/scion/workbench/src/lib/microfrontend-platform/routing/microfrontend-view-intent-interceptor.service.ts
=> fix(workbench/view): discard parameter if set to `undefined`

README.md
=> docs(workbench): update Angular compatibility overview

apps/workbench-client-testing-app/src/app/view-page/view-page.component.ts, apps/workbench-testing-app/src/app/workbench/throttle-capability-lookup-initializer.service.ts, package-lock.json, package.json, projects/scion/e2e-testing/src/app.po.ts, projects/scion/e2e-testing/src/workbench-client/view.e2e-spec.ts, projects/scion/workbench/package.json, projects/scion/workbench/src/lib/microfrontend-platform/microfrontend-popup/microfrontend-popup-intent-interceptor.service.ts, projects/scion/workbench/src/lib/microfrontend-platform/routing/microfrontend-view-intent-interceptor.service.ts
BREAKING CHANGE: updating `@scion/microfrontend-platform` to version `1.0.0-rc.7` introduced a breaking change.
To migrate, refer to the changelog of the SCION Microfrontend Platform: https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/blob/master/CHANGELOG.md#100-rc7-2022-10-07
=> deps: migrate to the asynchronous Interception API of `@scion/microfrontend-platform`

projects/scion/e2e-testing/src/workbench-client/router.e2e-spec.ts, projects/scion/workbench/src/lib/microfrontend-platform/microfrontend-view/microfrontend-view.component.ts
=> fix(workbench-client/router): set title/heading as passed to navigation

apps/workbench-client-testing-app/src/app/test-pages/test-pages-routing.module.ts, apps/workbench-client-testing-app/src/app/test-pages/view-properties-test-page/view-properties-test-page.component.ts, projects/scion/e2e-testing/src/helper/testing.util.ts, projects/scion/e2e-testing/src/popup.po.ts, projects/scion/e2e-testing/src/view-tab.po.ts, projects/scion/e2e-testing/src/workbench-client/view-properties.e2e-spec.ts, projects/scion/workbench-client/src/lib/view/workbench-view-capability.ts, projects/scion/workbench-client/src/lib/view/workbench-view.ts, projects/scion/workbench/src/lib/view/workbench-view.model.ts
=> test: add e2e tests for observable workbench view properties

apps/workbench-testing-app/src/app/app-routing.module.ts, apps/workbench-testing-app/src/app/blank/blank.component.ts, apps/workbench-testing-app/src/app/popup-opener-page/popup-opener-page.component.html, apps/workbench-testing-app/src/app/popup-opener-page/popup-opener-page.component.ts, apps/workbench-testing-app/src/app/router-page/router-page.component.html, apps/workbench-testing-app/src/app/test-pages/view-route-data-test-page/feature-routes.ts, apps/workbench-testing-app/src/app/test-pages/view-route-data-test-page/features-lazy.module.ts, apps/workbench-testing-app/src/app/test-pages/view-route-data-test-page/view-route-data-test-page.module.ts, projects/scion/e2e-testing/src/workbench-client/page-object/router-page.po.ts, projects/scion/e2e-testing/src/workbench-client/page-object/test-pages/bulk-navigation-test-page.po.ts, projects/scion/e2e-testing/src/workbench/navigational-state.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/page-object/popup-opener-page.po.ts, projects/scion/e2e-testing/src/workbench/page-object/router-page.po.ts, projects/scion/e2e-testing/src/workbench/page-object/test-pages/bulk-navigation-test-page.po.ts, projects/scion/e2e-testing/src/workbench/popup-position.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/popup.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/router.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/view-route-data.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/view-tab-bar.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/view.e2e-spec.ts, projects/scion/workbench/src/lib/routing/add-view-to-part.guard.ts, projects/scion/workbench/src/lib/routing/router.util.ts, projects/scion/workbench/src/lib/routing/workbench-route-data.ts, projects/scion/workbench/src/lib/view/view.component.ts
=> fix(workbench): allow defining view-specific route data in child routes of component-less routes

apps/workbench-testing-app/src/app/app.module.ts, apps/workbench-testing-app/src/app/workbench/workbench-lifecycle-hook-loggers.ts, package-lock.json, package.json, projects/scion/e2e-testing/src/workbench/workbench-lifecycle-hook.e2e-spec.ts, projects/scion/workbench/src/lib/microfrontend-platform/initialization/microfrontend-platform-initializer.service.ts, projects/scion/workbench/src/lib/startup/workbench-initializer.ts, projects/scion/workbench/src/lib/startup/workbench-launcher.service.ts, projects/scion/workbench/src/public-api.ts
=> feat(workbench): provide lifecycle hook to be invoked before starting the microfrontend platform

apps/workbench-testing-app/src/environments/environment.ts, apps/workbench-testing-app/src/environments/environment.vercel.ts
=> deps(workbench-testing-app): use DevTools v1.0.0-rc.12

projects/scion/workbench/src/lib/message-box/message-box.module.ts, projects/scion/workbench/src/lib/message-box/message-box.spec.ts, projects/scion/workbench/src/lib/spec/parts-layout.component.spec.ts
…oot injector
If the workbench was mounted via a standalone component using the Angular router, application-modal message boxes were not displayed.
=> fix(workbench/messagebox): fix registration of MessageBoxService in root injector

projects/scion/workbench/src/lib/view-part/view-tab-content/view-tab-content.component.scss
=> fix(workbench/view-tab): fix position of close button in view tabs

apps/workbench-testing-app/src/app/router-page/router-page.component.html, projects/scion/e2e-testing/src/workbench/router.e2e-spec.ts, projects/scion/workbench/src/lib/routing/workbench-router.service.ts
=> feat(workbench): allow for navigation to empty path auxiliary routes

projects/scion/workbench/src/lib/layout/workbench-layout.component.spec.ts, projects/scion/workbench/src/lib/message-box/message-box.spec.ts, projects/scion/workbench/src/lib/perspective/workbench-perspective-storage.spec.ts, projects/scion/workbench/src/lib/perspective/workbench-perspective-view-conflict-resolver.spec.ts, projects/scion/workbench/src/lib/perspective/workbench-perspective.spec.ts, projects/scion/workbench/src/lib/perspective/ɵworkbench-perspective.model.ts, projects/scion/workbench/src/lib/testing/testing.util.ts, projects/scion/workbench/src/lib/workbench.spec.ts
=> fix(workbench): display perspective also for asynchronous initial navigation

CHANGELOG_WORKBENCH.md, CHANGELOG_WORKBENCH_LATEST.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v16.0.0-beta.7

docs/site/howto/how-to-theme-workbench.md, projects/scion/workbench/design/_workbench-dark-theme-design-tokens.scss, projects/scion/workbench/design/_workbench-light-theme-design-tokens.scss, projects/scion/workbench/src/lib/part/view-tab/view-tab.component.scss
=> feat(workbench): enable customizing minimum tab width

apps/workbench-testing-app/src/environments/environment.ts, apps/workbench-testing-app/src/environments/environment.vercel.ts, package-lock.json, package.json, projects/scion/workbench/src/lib/microfrontend-platform/microfrontend-view/microfrontend-view.component.ts
=> fix(workbench-client): show splash if instructed by the capability, but only if not navigating to the same capability

apps/workbench-client-testing-app/src/app/app.component.ts, apps/workbench-client-testing-app/src/app/app.config.ts, apps/workbench-client-testing-app/src/app/theme/workbench-theme-switcher.service.ts, apps/workbench-client-testing-app/src/app/workbench-client/workbench-client.provider.ts
=> refactor(workbench-client-testing-app): consolidate theme activation

apps/workbench-testing-app/src/app/dialog-opener-page/dialog-opener-page.component.html, apps/workbench-testing-app/src/app/dialog-page/dialog-page.component.html, apps/workbench-testing-app/src/app/dialog-page/dialog-page.component.ts, projects/scion/e2e-testing/src/app.po.ts, projects/scion/e2e-testing/src/dialog-page.po.ts, projects/scion/e2e-testing/src/dialog.po.ts, projects/scion/e2e-testing/src/helper/testing.util.ts, projects/scion/e2e-testing/src/message-box.po.ts, projects/scion/e2e-testing/src/notification.po.ts, projects/scion/e2e-testing/src/part.po.ts, projects/scion/e2e-testing/src/popup.po.ts, projects/scion/e2e-testing/src/view.po.ts, projects/scion/e2e-testing/src/workbench-client/page-object/popup-opener-page.po.ts, projects/scion/e2e-testing/src/workbench/dialog.e2e-spec.ts, projects/scion/e2e-testing/src/workbench/page-object/popup-opener-page.po.ts, projects/scion/workbench/src/lib/common/observables.ts, projects/scion/workbench/src/lib/dialog/movable.directive.ts, projects/scion/workbench/src/lib/dialog/resizable.directive.ts, projects/scion/workbench/src/lib/dialog/workbench-dialog.component.html, projects/scion/workbench/src/lib/dialog/workbench-dialog.component.scss, projects/scion/workbench/src/lib/dialog/workbench-dialog.component.ts, projects/scion/workbench/src/lib/dialog/workbench-dialog.ts, projects/scion/workbench/src/lib/dialog/ɵworkbench-dialog.ts, projects/scion/workbench/tsconfig.lib.json
=> feat(workbench/dialog): make dialog resizable

apps/workbench-testing-app/src/app/dialog-page/dialog-page.component.html, apps/workbench-testing-app/src/app/dialog-page/dialog-page.component.scss, apps/workbench-testing-app/src/app/dialog-page/dialog-page.component.ts, projects/scion/e2e-testing/src/dialog-page.po.ts, projects/scion/e2e-testing/src/dialog.po.ts, projects/scion/e2e-testing/src/workbench/dialog.e2e-spec.ts, projects/scion/workbench/src/lib/dialog/workbench-dialog.component.html
=> test(workbench/dialog): test dialog size

apps/workbench-testing-app/src/environments/environment.ts, apps/workbench-testing-app/src/environments/environment.vercel.ts
=> deps(workbench-testing-app): use latest version of SCION Microfrontend Platform DevTools

apps/workbench-testing-app/src/app/app.config.ts, apps/workbench-testing-app/src/app/workbench.config.ts, apps/workbench-testing-app/src/app/workbench.perspectives.ts, apps/workbench-testing-app/src/app/workbench/workbench-startup-query-params.ts, projects/scion/workbench-client/src/lib/ɵworkbench-commands.ts, projects/scion/workbench/src/lib/layout/workbench-layouts.util.ts, projects/scion/workbench/src/lib/logging/logger-names.ts, projects/scion/workbench/src/lib/microfrontend-platform/routing/microfrontend-navigational-states.ts, projects/scion/workbench/src/lib/microfrontend-platform/routing/microfrontend-routes.ts, projects/scion/workbench/src/lib/routing/router.util.ts, projects/scion/workbench/src/lib/routing/workbench-navigational-states.ts, projects/scion/workbench/src/lib/routing/workbench-route-data.ts, projects/scion/workbench/src/lib/routing/workbench-router-link.directive.ts, projects/scion/workbench/src/lib/view-dnd/grid-drop-targets.util.ts
=> refactor(workbench): replace namespaces by object literals

projects/scion/workbench/src/lib/part/view-context-menu/view-menu.service.ts
In certain scenarios the 'keydown' event's key can be undefined.
=> fix(workbench): handle undefined 'keydown' event key

CHANGELOG_WORKBENCH_CLIENT.md, CHANGELOG_WORKBENCH_CLIENT_LATEST.md, docs/site/changelog-workbench-client/changelog.md, projects/scion/workbench-client/package.json
=> release(workbench-client): v1.0.0-beta.23

CHANGELOG_WORKBENCH.md, CHANGELOG_WORKBENCH_LATEST.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v17.0.0-beta.9

README.md
=> docs(workbench): update version compatibility list for Angular 18

.github/workflows/workflow.yml, CONTRIBUTING.md
=> chore: update Node.js version for contribution and CI/CD

CHANGELOG_WORKBENCH.md, CHANGELOG_WORKBENCH_LATEST.md, docs/site/changelog-workbench/changelog.md, projects/scion/workbench/package.json
=> release(workbench): v18.0.0-beta.2

projects/scion/e2e-testing/src/view-tab-context-menu.po.ts, projects/scion/workbench/src/lib/part/view-context-menu/text.component.ts, projects/scion/workbench/src/lib/part/view-context-menu/view-menu.service.ts, projects/scion/workbench/src/lib/view/view.menu.spec.ts, projects/scion/workbench/src/lib/workbench-config.ts
=> feat(workbench/view): enable translation of built-in context menu

projects/scion/e2e-testing/src/part.po.ts, projects/scion/e2e-testing/src/view-tab.po.ts, projects/scion/e2e-testing/src/workbench/view-tab-bar.e2e-spec.ts, projects/scion/workbench/src/lib/layout/migration/model/workbench-layout-migration-v6.model.ts, projects/scion/workbench/src/lib/layout/migration/workbench-layout-migration-v5.service.ts, projects/scion/workbench/src/lib/layout/migration/workbench-layout-migration-v6.service.ts, projects/scion/workbench/src/lib/layout/workbench-layout.model.ts, projects/scion/workbench/src/lib/layout/workbench-layout.spec.ts, projects/scion/workbench/src/lib/layout/workench-layout-serializer.service.spec.ts, projects/scion/workbench/src/lib/layout/workench-layout-serializer.service.ts, projects/scion/workbench/src/lib/layout/ɵworkbench-layout.ts, projects/scion/workbench/src/lib/part/part-bar/part-bar.component.html, projects/scion/workbench/src/lib/part/part-bar/part-bar.component.ts, projects/scion/workbench/src/lib/part/view-list-button/view-list-button.component.html, projects/scion/workbench/src/lib/perspective/workbench-grid-merger.service.ts, projects/scion/workbench/src/lib/routing/workbench-router.spec.ts, projects/scion/workbench/src/lib/view/view.spec.ts, projects/scion/workbench/src/lib/view/ɵworkbench-view.model.ts
- fix(workbench/view): do not scroll the active tab into view when opening or closing an inactive tab
- fix(workbench/view): scroll active tab into view when navigating
=> fix(workbench/view): do not scroll the active tab into view when opening or closing an inactive tab

CHANGELOG_WORKBENCH.md, CHANGELOG_WORKBENCH_LATEST.md, docs/site/changelog-workbench/changelog.md
=> release(workbench): v19.0.0-beta.1

.github/workflows/workflow.yml, projects/scion/e2e-testing/playwright.config.ts
=> ci: upload Playwright video on failure
